[project]
name = "datalogger-jupyterlab"
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Framework :: Jupyter",
  "Framework :: Jupyter :: JupyterLab",
  "Framework :: Jupyter :: JupyterLab :: 4",
  "Framework :: Jupyter :: JupyterLab :: Extensions",
  "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
  "License :: OSI Approved :: BSD License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dependencies = []
dynamic = ["version", "description", "authors", "keywords", "urls"]

[tool.hatch.version]
source = "nodejs"

[tool.hatch.metadata.hooks.nodejs]
fields = ["description", "authors", "urls", "keywords"]

[tool.hatch.build.targets.sdist]
artifacts = ["/labextension"]
exclude = ["**/*"]

[tool.hatch.build.targets.wheel.shared-data]
"labextension" = "share/jupyter/labextensions/datalogger-jupyterlab"
"install.json" = "share/jupyter/labextensions/datalogger-jupyterlab/install.json"

[tool.hatch.envs.default]
dependencies = [
  "jupyterlab>=4.0.6,<5",
  "jupyterlab-lsp>=5.0.0rc0,<6",
  "python-lsp-server[flake8]>=1.8.0,<2",
  "pylsp-mypy>=0.6.7,<0.7",
  "datalogger>=0.1.1",
  "numpy>=1.25.2,<2",
  "xarray>=2023.8.0",
  "matplotlib>=3.7.3,<4"
]

[tool.hatch.envs.default.env-vars]
PIP_EXTRA_INDEX_URL = "https://painterqubits.github.io/datalogger/releases"

[build-system]
requires = ["hatchling", "hatch-nodejs-version"]
build-backend = "hatchling.build"
