[project]
name = "datalogger-jupyterlab"
version = "0.1.0"
description = "JupyterLab extension for DataLogger."
readme = "README.md"
requires-python = ">=3.9"
license = "BSD-3-Clause"
keywords = ["jupyter", "jupyterlab", "jupyterlab-extension"]
authors = [
  { name = "Alex Hadley", email = "alexhad6@gmail.com" },
]
classifiers = [
  "Framework :: Jupyter",
  "Framework :: Jupyter :: JupyterLab",
  "Framework :: Jupyter :: JupyterLab :: 4",
  "Framework :: Jupyter :: JupyterLab :: Extensions",
  "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
  "License :: OSI Approved :: BSD License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/PainterQubits/datalogger-jupyterlab-exploration#readme"
Issues = "https://github.com/PainterQubits/datalogger-jupyterlab-exploration/issues"
Source = "https://github.com/PainterQubits/datalogger-jupyterlab-exploration"

[tool.hatch.build.targets.sdist]
artifacts = ["/labextension"]
exclude = ["package.json", "yarn.lock"]

[tool.hatch.build.targets.wheel.shared-data]
"labextension" = "share/jupyter/labextensions/datalogger_jupyterlab"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
